---
- hosts: all
  become: true
  gather_facts: no
  vars:
    sap_control_function: "restart_all_sap"
  
  tasks:

    - name: 'run sap_control'
      ansible.builtin.include_role:
    name: community.sap_operations.sap_control
    

