---
- hosts: all
  become: true
  gather_facts: no
  #vars:
   # sap_control_function: "restart_all_sap"
  # test comment
  tasks:

    - name: copy files to /tmp
      copy:
        remote_src: "/var/lib/insights/{{ item }}"
        dest: /tmp/
      with_items:
        - "last_stable.egg*"
        - "newest.eg*"

    - name: register insights-client
      shell: "insights-client --register --display-name=SAPdemo-{{ inventory_hostname }} --force"
      
      



