---
- hosts: all
  become: true
  gather_facts: true
  vars:
    EggFiles:
      - name: last_stable.egg
      - name: last_stable.egg.asc
      - name: newest.egg
      - name: newest.egg.asc
   # sap_control_function: "restart_all_sap"
  # test comment 2
  tasks:
    - name: check existing file Name
      stat: 
        path: /var/lib/insights/{{ item.name }}
      debug:
        msg: "{{ item.name }} exists"
      with_items: "{{ EggFiles }}"
      register: CheckFileName
    - name: copy files to /tmp if they existing
      copy:
        src: "/var/lib/insights/{{ item.name }}"
        remote_src: yes
        dest: "/tmp"
      with_items: "{{ CheckFileName.results }}"
      when: item.stat.exists
    - name: register Red Hat insights-client
      shell: "insights-client --register --display-name=SAPdemo-{{ inventory_hostname }} --force"
      
      



