---

# Experimental Ansible Role, do not suggest using this

- hosts: all
  become: true
  pre_tasks:
#    - include_vars: ./vars/sample-variables-sap-storage-lvm.yml
#    - include_vars: ./vars/sample-variables-sap-storage-lvm-stripes.yml

  tasks:

  - name: SAP storage preparation
    vars:
      sap_storage_cloud_type: 'generic'
      sap_storage_sap_type: 'sap_onehost'
      sap_storage_action: 'prepare'
    include_role: 
      name: ../roles/sap_storage_setup
