---
# Phase 3 - step B
#
# The role sap_hana_install unpacks the software in {{ sap_hana_install_software_directory }}
# Then it calls the installation of SAP HANA with the configured paramters

- name: Phase 3-B - Install Hana
  hosts: hanas
  become: true
  vars:
#    sap_domain: example.com
#
    sap_hana_sid: 'DB1'
    sap_hana_instance_number: '00'
  tasks:
    # This step is already included in version 1.0.2. of the collection
    # name: Detect Existing HANA installation
    #  include_tasks: check_for_sap_instances.yml

    - name: execute the SAP Hana Installation
      include_role:
        name: community.sap_install.sap_hana_install
    # when: not sap_hana_deployment_skip
